<?php
// Migrations for RestoCloud
// NOTE: ALTER TABLE ADD COLUMN, CREATE INDEX, and ADD UNIQUE INDEX do NOT use
// IF NOT EXISTS because MySQL 5.7 does not support it. The try/catch in db.php
// handles duplicate column/index errors gracefully. CREATE TABLE IF NOT EXISTS
// is fine in all MySQL versions.
return [
    'v1_add_caja_cierres_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `almuerzos_vendidos` INT NOT NULL DEFAULT 0",
    'v2_add_segundos_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `segundos_vendidos` INT NOT NULL DEFAULT 0",
    'v3_add_sopas_vendidas' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `sopas_vendidas` INT NOT NULL DEFAULT 0",
    'v4_add_extras_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `extras_vendidos` INT NOT NULL DEFAULT 0",
    'v5_add_pedidos_closure_id' => "ALTER TABLE `pedidos` ADD COLUMN `closure_id` VARCHAR(50) NULL",
    'v6_add_caja_movimientos_closure_id' => "ALTER TABLE `caja_movimientos` ADD COLUMN `closure_id` VARCHAR(50) NULL",
    'v7_index_pedidos_status_closure_timestamp' => "CREATE INDEX `idx_pedidos_status_closure_timestamp` ON `pedidos` (`status`, `closure_id`, `timestamp`)",
    'v8_index_caja_movimientos_closure_timestamp' => "CREATE INDEX `idx_caja_movimientos_closure_timestamp` ON `caja_movimientos` (`closure_id`, `timestamp`)",
    'v9_index_caja_cierres_timestamp' => "CREATE INDEX `idx_caja_cierres_timestamp` ON `caja_cierres_historico` (`timestamp`)",
    'v10_create_menus_table' => "CREATE TABLE IF NOT EXISTS `menus` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `start_time` TIME DEFAULT NULL,
        `end_time` TIME DEFAULT NULL,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v11_create_products_table' => "CREATE TABLE IF NOT EXISTS `products` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(150) NOT NULL,
        `type` ENUM('sopa','segundo','plato_extra','refresco') NOT NULL,
        `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `stock` INT NOT NULL DEFAULT 0,
        `menu_id` VARCHAR(50) DEFAULT NULL,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_products_type` (`type`),
        INDEX `idx_products_menu` (`menu_id`),
        FOREIGN KEY (`menu_id`) REFERENCES `menus`(`id`) ON DELETE SET NULL
    )",
    'v12_insert_default_menu' => "INSERT IGNORE INTO `menus` (`id`, `name`, `active`) VALUES ('default', 'Menú del Día', 1)",
    'v13_migrate_segundos_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'segundo', 0, `stock`, 'default' FROM `segundos`",
    'v14_migrate_platos_extras_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'plato_extra', `price`, `stock`, 'default' FROM `platos_extras`",
    'v15_migrate_gaseosas_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'refresco', `price`, `stock`, 'default' FROM `gaseosas`",
    'v16_migrate_sopa_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT CONCAT('sopa_', `total`), 'Sopa del Día', 'sopa', (SELECT `valor` FROM `config_precios` WHERE `id` = 'sopa' LIMIT 1), `total`, 'default' FROM `inventario_sopa` WHERE `total` > 0",
    'v17_create_tables_config' => "CREATE TABLE IF NOT EXISTS `tables_config` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `icon` VARCHAR(50) NOT NULL DEFAULT 'fa-chair',
        `sort_order` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v18_seed_default_tables' => "INSERT IGNORE INTO `tables_config` (`id`, `name`, `icon`, `sort_order`) VALUES
        ('tbl_1', 'Mesa 1', 'fa-chair', 1),
        ('tbl_2', 'Mesa 2', 'fa-chair', 2),
        ('tbl_3', 'Mesa 3', 'fa-chair', 3),
        ('tbl_4', 'Mesa 4', 'fa-chair', 4),
        ('tbl_bar1', 'Barra 1', 'fa-couch', 5),
        ('tbl_bar2', 'Barra 2', 'fa-couch', 6),
        ('tbl_llevar', 'Llevar', 'fa-bag-shopping', 7)",
    'v19_add_segundos_active_column' => "ALTER TABLE `segundos` ADD COLUMN `active` TINYINT(1) NOT NULL DEFAULT 1",
    'v20_create_sopas_table' => "CREATE TABLE IF NOT EXISTS `sopas` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(150) NOT NULL,
        `stock` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1
    )",
    'v21_add_tenant_branch_to_config_precios' => "ALTER TABLE `config_precios` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v22_add_tenant_branch_to_config_general' => "ALTER TABLE `config_general` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v23_add_tenant_branch_to_inventario_sopa' => "ALTER TABLE `inventario_sopa` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v24_add_tenant_branch_to_segundos' => "ALTER TABLE `segundos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v25_add_tenant_branch_to_platos_extras' => "ALTER TABLE `platos_extras` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v26_add_tenant_branch_to_gaseosas' => "ALTER TABLE `gaseosas` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v27_add_tenant_branch_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v28_add_tenant_branch_to_caja_movimientos' => "ALTER TABLE `caja_movimientos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v29_add_tenant_branch_to_caja_cierres' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v30_add_tenant_branch_to_menus' => "ALTER TABLE `menus` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v31_add_tenant_branch_to_products' => "ALTER TABLE `products` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v32_add_tenant_branch_to_tables' => "ALTER TABLE `tables_config` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v33_add_tenant_branch_to_sopas' => "ALTER TABLE `sopas` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v34_index_config_precios_tenant_branch' => "CREATE INDEX `idx_config_precios_tenant_branch` ON `config_precios` (`tenant_id`, `branch_id`, `id`)",
    'v35_index_config_general_tenant_branch' => "CREATE INDEX `idx_config_general_tenant_branch` ON `config_general` (`tenant_id`, `branch_id`, `id`)",
    'v36_index_inventario_sopa_tenant_branch' => "CREATE INDEX `idx_inventario_sopa_tenant_branch` ON `inventario_sopa` (`tenant_id`, `branch_id`)",
    'v37_index_segundos_tenant_branch' => "CREATE INDEX `idx_segundos_tenant_branch` ON `segundos` (`tenant_id`, `branch_id`, `active`)",
    'v38_index_platos_extras_tenant_branch' => "CREATE INDEX `idx_platos_extras_tenant_branch` ON `platos_extras` (`tenant_id`, `branch_id`)",
    'v39_index_gaseosas_tenant_branch' => "CREATE INDEX `idx_gaseosas_tenant_branch` ON `gaseosas` (`tenant_id`, `branch_id`)",
    'v40_index_pedidos_tenant_branch_status' => "CREATE INDEX `idx_pedidos_tenant_branch_status` ON `pedidos` (`tenant_id`, `branch_id`, `status`, `closure_id`, `timestamp`)",
    'v41_index_caja_movimientos_tenant_branch' => "CREATE INDEX `idx_caja_movimientos_tenant_branch` ON `caja_movimientos` (`tenant_id`, `branch_id`, `closure_id`, `timestamp`)",
    'v42_index_caja_cierres_tenant_branch' => "CREATE INDEX `idx_caja_cierres_tenant_branch` ON `caja_cierres_historico` (`tenant_id`, `branch_id`, `timestamp`)",
    'v43_index_menus_tenant_branch' => "CREATE INDEX `idx_menus_tenant_branch` ON `menus` (`tenant_id`, `branch_id`, `active`)",
    'v44_index_products_tenant_branch' => "CREATE INDEX `idx_products_tenant_branch` ON `products` (`tenant_id`, `branch_id`, `active`, `menu_id`)",
    'v45_index_tables_tenant_branch' => "CREATE INDEX `idx_tables_tenant_branch` ON `tables_config` (`tenant_id`, `branch_id`, `active`, `sort_order`)",
    'v46_index_sopas_tenant_branch' => "CREATE INDEX `idx_sopas_tenant_branch` ON `sopas` (`tenant_id`, `branch_id`, `active`)",
    'v47_create_reservations_table' => "CREATE TABLE IF NOT EXISTS `reservations` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `customer_name` VARCHAR(150) NOT NULL,
        `phone` VARCHAR(30) DEFAULT NULL,
        `party_size` INT NOT NULL DEFAULT 1,
        `reservation_date` DATE NOT NULL,
        `reservation_time` TIME NOT NULL,
        `table_id` VARCHAR(50) DEFAULT NULL,
        `status` ENUM('pendiente','confirmada','cancelada','completada') NOT NULL DEFAULT 'pendiente',
        `notes` TEXT DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX `idx_reservations_tenant_branch_date` (`tenant_id`, `branch_id`, `reservation_date`, `status`),
        INDEX `idx_reservations_status` (`status`)
    )",
    'v48_add_items_total_to_reservations' => "ALTER TABLE `reservations` ADD COLUMN `items` LONGTEXT DEFAULT NULL, ADD COLUMN `total` DECIMAL(10,2) NOT NULL DEFAULT 0.00",
    'v49_add_business_type_plan_level' => "ALTER TABLE `tenants` ADD COLUMN `business_type` VARCHAR(50) DEFAULT 'restaurante', ADD COLUMN `plan_level` ENUM('basico','premium','enterprise') DEFAULT 'basico'",
    'v50_unify_roles_to_three' => "UPDATE `users` SET `role` = 'cajero' WHERE `role` = 'cocina'",
    'v51_add_super_admin_role' => "ALTER TABLE `users` MODIFY COLUMN `role` ENUM('super_admin','owner','admin','cajero') NOT NULL DEFAULT 'owner'",
    'v52_seed_owner_to_super_admin' => "UPDATE `users` SET `role` = 'super_admin' WHERE `email` = 'owner@legacy.restocloud.local' AND `role` = 'owner'",
    // v53: UNIQUE constraints — split into individual migrations per table for MySQL 5.7 compat
    'v53a_add_unique_segundos' => "ALTER TABLE `segundos` ADD UNIQUE INDEX `uniq_segundos_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53b_add_unique_sopas' => "ALTER TABLE `sopas` ADD UNIQUE INDEX `uniq_sopas_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53c_add_unique_platos_extras' => "ALTER TABLE `platos_extras` ADD UNIQUE INDEX `uniq_platos_extras_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53d_add_unique_gaseosas' => "ALTER TABLE `gaseosas` ADD UNIQUE INDEX `uniq_gaseosas_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53e_add_unique_products' => "ALTER TABLE `products` ADD UNIQUE INDEX `uniq_products_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53f_add_unique_menus' => "ALTER TABLE `menus` ADD UNIQUE INDEX `uniq_menus_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53g_add_unique_tables' => "ALTER TABLE `tables_config` ADD UNIQUE INDEX `uniq_tables_config_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v54_unique_closure_per_day' => "ALTER TABLE `caja_cierres_historico` ADD UNIQUE INDEX `uniq_cierre_per_day` (`tenant_id`, `branch_id`, `fecha`)",
    'v55_create_categories_table' => "CREATE TABLE IF NOT EXISTS `categories` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `name` VARCHAR(100) NOT NULL,
        `type` ENUM('sopa','segundo','plato_extra','refresco','general') NOT NULL DEFAULT 'general',
        `sort_order` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE INDEX `uniq_categories_tenant_branch` (`tenant_id`, `branch_id`, `id`),
        INDEX `idx_categories_tenant_type` (`tenant_id`, `branch_id`, `type`, `active`)
    )",
    'v56_add_category_id_to_products' => "ALTER TABLE `products` ADD COLUMN `category_id` VARCHAR(50) DEFAULT NULL",
    // v57: Stock history tracking for multi-day stock management
    'v57_create_stock_history' => "CREATE TABLE IF NOT EXISTS stock_history (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            item_type ENUM('segundo','sopa','plato_extra','gaseosa') NOT NULL,
            item_id VARCHAR(50) NOT NULL,
            event_type ENUM('set','deduct','restore','adjust') NOT NULL,
            quantity_before INT NOT NULL,
            quantity_change INT NOT NULL,
            quantity_after INT NOT NULL,
            reference_type VARCHAR(50),
            reference_id VARCHAR(50),
            created_at DATETIME NOT NULL,
            INDEX idx_stock_history_item (tenant_id, branch_id, item_type, item_id, created_at),
            INDEX idx_stock_history_date (tenant_id, branch_id, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v58_create_stock_daily_snapshot' => "CREATE TABLE IF NOT EXISTS stock_daily_snapshot (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            item_type ENUM('segundo','sopa','plato_extra','gaseosa') NOT NULL,
            item_id VARCHAR(50) NOT NULL,
            item_name VARCHAR(255) NOT NULL DEFAULT '',
            snapshot_date DATE NOT NULL,
            opening_stock INT NOT NULL,
            closing_stock INT NOT NULL,
            sold_count INT NOT NULL DEFAULT 0,
            UNIQUE KEY uniq_snapshot (tenant_id, branch_id, item_type, item_id, snapshot_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v59_create_discounts' => "CREATE TABLE IF NOT EXISTS discounts (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            name VARCHAR(255) NOT NULL,
            type ENUM('percentage', 'fixed', 'buy_x_get_y') NOT NULL DEFAULT 'percentage',
            value DECIMAL(10,2) NOT NULL DEFAULT 0,
            min_quantity INT NOT NULL DEFAULT 0,
            free_quantity INT NOT NULL DEFAULT 0,
            applicable_types JSON,
            start_date DATE DEFAULT NULL,
            end_date DATE DEFAULT NULL,
            active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_discounts_tenant (tenant_id, branch_id, active),
            INDEX idx_discounts_dates (start_date, end_date, active)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v60_add_delivery_type_to_reservations' => "ALTER TABLE `reservations` ADD COLUMN `delivery_type` ENUM('para_servirse','para_llevar') NOT NULL DEFAULT 'para_servirse'",
    'v61_add_delivery_type_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `delivery_type` ENUM('mesa','llevar','delivery') NOT NULL DEFAULT 'mesa'",
    // v62: UNIQUE constraints per table (for databases that already ran old v53)
    'v62_fix_tenant_unique_constraints' => "ALTER TABLE `sopas` ADD UNIQUE INDEX `uniq_sopas_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62b_fix_tenant_unique_constraints_platos' => "ALTER TABLE `platos_extras` ADD UNIQUE INDEX `uniq_platos_extras_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62c_fix_tenant_unique_constraints_gaseosas' => "ALTER TABLE `gaseosas` ADD UNIQUE INDEX `uniq_gaseosas_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62d_fix_tenant_unique_constraints_products' => "ALTER TABLE `products` ADD UNIQUE INDEX `uniq_products_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62e_fix_tenant_unique_constraints_menus' => "ALTER TABLE `menus` ADD UNIQUE INDEX `uniq_menus_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62f_fix_tenant_unique_constraints_tables' => "ALTER TABLE `tables_config` ADD UNIQUE INDEX `uniq_tables_config_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    // v63: Add service_state to pedidos for existing databases created before db.php included it
    'v63_add_service_state_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `service_state` VARCHAR(50) DEFAULT NULL",
    'v64_create_salsas_table' => "CREATE TABLE IF NOT EXISTS `salsas` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `tenant_id` VARCHAR(50) NULL,
        `branch_id` VARCHAR(50) NULL
    )",
    'v65_add_accepts_salsa_to_segundos' => "ALTER TABLE `segundos` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v66_add_accepts_salsa_to_sopas' => "ALTER TABLE `sopas` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v67_add_accepts_salsa_to_platos_extras' => "ALTER TABLE `platos_extras` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v68_add_salsa_to_stock_history_enum' => "ALTER TABLE `stock_history` MODIFY COLUMN `item_type` ENUM('segundo','sopa','plato_extra','gaseosa','salsa') NOT NULL",
    'v69_fix_config_precios_pk' => "ALTER TABLE `config_precios` DROP PRIMARY KEY, ADD UNIQUE KEY `uniq_precio` (`id`, `tenant_id`, `branch_id`)",
    'v70_fix_config_general_pk' => "ALTER TABLE `config_general` DROP PRIMARY KEY, ADD UNIQUE KEY `uniq_general` (`id`, `tenant_id`, `branch_id`)",
    'v74_add_paid_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `paid` TINYINT(1) NOT NULL DEFAULT 0",
    'v75_add_pais_to_config_general' => "INSERT IGNORE INTO `config_general` (`id`, `value`) VALUES ('pais', 'Bolivia')",
    'v76_add_trial_days_to_plans' => "ALTER TABLE `plans` ADD COLUMN `trial_days` INT NOT NULL DEFAULT 14",
    'v77_add_plan_snapshot_to_subscriptions' => "ALTER TABLE `tenant_subscriptions` ADD COLUMN `plan_snapshot` JSON DEFAULT NULL",
    'v78_create_plan_changes_log' => "CREATE TABLE IF NOT EXISTS `plan_changes_log` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `old_plan_id` VARCHAR(50) DEFAULT NULL,
        `new_plan_id` VARCHAR(50) DEFAULT NULL,
        `old_snapshot` JSON DEFAULT NULL,
        `new_snapshot` JSON DEFAULT NULL,
        `changed_by` VARCHAR(50) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v79_add_payment_verification_to_subscriptions' => "ALTER TABLE `tenant_subscriptions`
        ADD COLUMN `payment_method` VARCHAR(30) DEFAULT NULL,
        ADD COLUMN `payment_notes` TEXT DEFAULT NULL,
        ADD COLUMN `verified_by` VARCHAR(100) DEFAULT NULL,
        ADD COLUMN `verified_at` DATETIME DEFAULT NULL",
];
