<?php
// Migrations for RestoCloud
// NOTE: ALTER TABLE ADD COLUMN, CREATE INDEX, and ADD UNIQUE INDEX do NOT use
// IF NOT EXISTS because MySQL 5.7 does not support it. The try/catch in db.php
// handles duplicate column/index errors gracefully. CREATE TABLE IF NOT EXISTS
// is fine in all MySQL versions.
return [
    'v98_ensure_financial_expenses_table' => "CREATE TABLE IF NOT EXISTS `gastos_financieros` (
        `id` VARCHAR(50) PRIMARY KEY,
        `fecha` DATE NOT NULL,
        `description` VARCHAR(255) NOT NULL,
        `category` VARCHAR(50) NOT NULL DEFAULT 'otros',
        `amount` DECIMAL(10,2) NOT NULL,
        `payment_method` VARCHAR(30) NOT NULL DEFAULT 'efectivo',
        `reference` VARCHAR(120) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_by` VARCHAR(26) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_gastos_financieros_scope_date` (`tenant_id`, `branch_id`, `fecha`)
    )",
    'v88_create_financial_expenses' => "CREATE TABLE IF NOT EXISTS `gastos_financieros` (
        `id` VARCHAR(50) PRIMARY KEY,
        `fecha` DATE NOT NULL,
        `description` VARCHAR(255) NOT NULL,
        `category` VARCHAR(50) NOT NULL DEFAULT 'otros',
        `amount` DECIMAL(10,2) NOT NULL,
        `payment_method` VARCHAR(30) NOT NULL DEFAULT 'efectivo',
        `reference` VARCHAR(120) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_by` VARCHAR(26) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_gastos_financieros_scope_date` (`tenant_id`, `branch_id`, `fecha`)
    )",
    'v1_add_caja_cierres_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `almuerzos_vendidos` INT NOT NULL DEFAULT 0",
    'v2_add_segundos_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `segundos_vendidos` INT NOT NULL DEFAULT 0",
    'v3_add_sopas_vendidas' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `sopas_vendidas` INT NOT NULL DEFAULT 0",
    'v4_add_extras_vendidos' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `extras_vendidos` INT NOT NULL DEFAULT 0",
    'v5_add_pedidos_closure_id' => "ALTER TABLE `pedidos` ADD COLUMN `closure_id` VARCHAR(50) NULL",
    'v6_add_caja_movimientos_closure_id' => "ALTER TABLE `caja_movimientos` ADD COLUMN `closure_id` VARCHAR(50) NULL",
    'v7_index_pedidos_status_closure_timestamp' => "CREATE INDEX `idx_pedidos_status_closure_timestamp` ON `pedidos` (`status`, `closure_id`, `timestamp`)",
    'v8_index_caja_movimientos_closure_timestamp' => "CREATE INDEX `idx_caja_movimientos_closure_timestamp` ON `caja_movimientos` (`closure_id`, `timestamp`)",
    'v9_index_caja_cierres_timestamp' => "CREATE INDEX `idx_caja_cierres_timestamp` ON `caja_cierres_historico` (`timestamp`)",
    'v10_create_menus_table' => "CREATE TABLE IF NOT EXISTS `menus` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `start_time` TIME DEFAULT NULL,
        `end_time` TIME DEFAULT NULL,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v11_create_products_table' => "CREATE TABLE IF NOT EXISTS `products` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(150) NOT NULL,
        `type` ENUM('sopa','segundo','plato_extra','refresco','salsa','acompanamiento') NOT NULL,
        `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `stock` INT NOT NULL DEFAULT 0,
        `menu_id` VARCHAR(50) DEFAULT NULL,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_products_type` (`type`),
        INDEX `idx_products_menu` (`menu_id`),
        FOREIGN KEY (`menu_id`) REFERENCES `menus`(`id`) ON DELETE SET NULL
    )",
    'v12_insert_default_menu' => "INSERT IGNORE INTO `menus` (`id`, `name`, `active`) VALUES ('default', 'Menú del Día', 1)",
    'v13_migrate_segundos_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'segundo', 0, `stock`, 'default' FROM `segundos`",
    'v14_migrate_platos_extras_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'plato_extra', `price`, `stock`, 'default' FROM `platos_extras`",
    'v15_migrate_gaseosas_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT `id`, `name`, 'refresco', `price`, `stock`, 'default' FROM `gaseosas`",
    'v16_migrate_sopa_to_products' => "INSERT IGNORE INTO `products` (`id`, `name`, `type`, `price`, `stock`, `menu_id`)
        SELECT CONCAT('sopa_', `total`), 'Sopa del Día', 'sopa', (SELECT `valor` FROM `config_precios` WHERE `id` = 'sopa' LIMIT 1), `total`, 'default' FROM `inventario_sopa` WHERE `total` > 0",
    'v17_create_tables_config' => "CREATE TABLE IF NOT EXISTS `tables_config` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `icon` VARCHAR(50) NOT NULL DEFAULT 'fa-chair',
        `sort_order` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v18_seed_default_tables' => "INSERT IGNORE INTO `tables_config` (`id`, `name`, `icon`, `sort_order`) VALUES
        ('tbl_1', 'Mesa 1', 'fa-chair', 1),
        ('tbl_2', 'Mesa 2', 'fa-chair', 2),
        ('tbl_3', 'Mesa 3', 'fa-chair', 3),
        ('tbl_4', 'Mesa 4', 'fa-chair', 4),
        ('tbl_bar1', 'Barra 1', 'fa-couch', 5),
        ('tbl_bar2', 'Barra 2', 'fa-couch', 6),
        ('tbl_llevar', 'Llevar', 'fa-bag-shopping', 7)",
    'v19_add_segundos_active_column' => "ALTER TABLE `segundos` ADD COLUMN `active` TINYINT(1) NOT NULL DEFAULT 1",
    'v20_create_sopas_table' => "CREATE TABLE IF NOT EXISTS `sopas` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(150) NOT NULL,
        `stock` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1
    )",
    'v21_add_tenant_branch_to_config_precios' => "ALTER TABLE `config_precios` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v22_add_tenant_branch_to_config_general' => "ALTER TABLE `config_general` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v23_add_tenant_branch_to_inventario_sopa' => "ALTER TABLE `inventario_sopa` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v24_add_tenant_branch_to_segundos' => "ALTER TABLE `segundos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v25_add_tenant_branch_to_platos_extras' => "ALTER TABLE `platos_extras` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v26_add_tenant_branch_to_gaseosas' => "ALTER TABLE `gaseosas` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v27_add_tenant_branch_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v28_add_tenant_branch_to_caja_movimientos' => "ALTER TABLE `caja_movimientos` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v29_add_tenant_branch_to_caja_cierres' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v30_add_tenant_branch_to_menus' => "ALTER TABLE `menus` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v31_add_tenant_branch_to_products' => "ALTER TABLE `products` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v32_add_tenant_branch_to_tables' => "ALTER TABLE `tables_config` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v33_add_tenant_branch_to_sopas' => "ALTER TABLE `sopas` ADD COLUMN `tenant_id` VARCHAR(50) NULL, ADD COLUMN `branch_id` VARCHAR(50) NULL",
    'v34_index_config_precios_tenant_branch' => "CREATE INDEX `idx_config_precios_tenant_branch` ON `config_precios` (`tenant_id`, `branch_id`, `id`)",
    'v35_index_config_general_tenant_branch' => "CREATE INDEX `idx_config_general_tenant_branch` ON `config_general` (`tenant_id`, `branch_id`, `id`)",
    'v36_index_inventario_sopa_tenant_branch' => "CREATE INDEX `idx_inventario_sopa_tenant_branch` ON `inventario_sopa` (`tenant_id`, `branch_id`)",
    'v37_index_segundos_tenant_branch' => "CREATE INDEX `idx_segundos_tenant_branch` ON `segundos` (`tenant_id`, `branch_id`, `active`)",
    'v38_index_platos_extras_tenant_branch' => "CREATE INDEX `idx_platos_extras_tenant_branch` ON `platos_extras` (`tenant_id`, `branch_id`)",
    'v39_index_gaseosas_tenant_branch' => "CREATE INDEX `idx_gaseosas_tenant_branch` ON `gaseosas` (`tenant_id`, `branch_id`)",
    'v40_index_pedidos_tenant_branch_status' => "CREATE INDEX `idx_pedidos_tenant_branch_status` ON `pedidos` (`tenant_id`, `branch_id`, `status`, `closure_id`, `timestamp`)",
    'v41_index_caja_movimientos_tenant_branch' => "CREATE INDEX `idx_caja_movimientos_tenant_branch` ON `caja_movimientos` (`tenant_id`, `branch_id`, `closure_id`, `timestamp`)",
    'v42_index_caja_cierres_tenant_branch' => "CREATE INDEX `idx_caja_cierres_tenant_branch` ON `caja_cierres_historico` (`tenant_id`, `branch_id`, `timestamp`)",
    'v43_index_menus_tenant_branch' => "CREATE INDEX `idx_menus_tenant_branch` ON `menus` (`tenant_id`, `branch_id`, `active`)",
    'v44_index_products_tenant_branch' => "CREATE INDEX `idx_products_tenant_branch` ON `products` (`tenant_id`, `branch_id`, `active`, `menu_id`)",
    'v45_index_tables_tenant_branch' => "CREATE INDEX `idx_tables_tenant_branch` ON `tables_config` (`tenant_id`, `branch_id`, `active`, `sort_order`)",
    'v46_index_sopas_tenant_branch' => "CREATE INDEX `idx_sopas_tenant_branch` ON `sopas` (`tenant_id`, `branch_id`, `active`)",
    'v47_create_reservations_table' => "CREATE TABLE IF NOT EXISTS `reservations` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `customer_name` VARCHAR(150) NOT NULL,
        `phone` VARCHAR(30) DEFAULT NULL,
        `party_size` INT NOT NULL DEFAULT 1,
        `reservation_date` DATE NOT NULL,
        `reservation_time` TIME NOT NULL,
        `table_id` VARCHAR(50) DEFAULT NULL,
        `status` ENUM('pendiente','confirmada','cancelada','completada') NOT NULL DEFAULT 'pendiente',
        `notes` TEXT DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX `idx_reservations_tenant_branch_date` (`tenant_id`, `branch_id`, `reservation_date`, `status`),
        INDEX `idx_reservations_status` (`status`)
    )",
    'v48_add_items_total_to_reservations' => "ALTER TABLE `reservations` ADD COLUMN `items` LONGTEXT DEFAULT NULL, ADD COLUMN `total` DECIMAL(10,2) NOT NULL DEFAULT 0.00",
    'v49_add_business_type_plan_level' => "ALTER TABLE `tenants` ADD COLUMN `business_type` VARCHAR(50) DEFAULT 'restaurante', ADD COLUMN `plan_level` ENUM('basico','premium','enterprise') DEFAULT 'basico'",
    'v50_unify_roles_to_three' => "UPDATE `users` SET `role` = 'cajero' WHERE `role` = 'cocina'",
    'v51_add_super_admin_role' => "ALTER TABLE `users` MODIFY COLUMN `role` ENUM('super_admin','owner','admin','cajero') NOT NULL DEFAULT 'owner'",
    'v52_seed_owner_to_super_admin' => "UPDATE `users` SET `role` = 'super_admin' WHERE `email` = 'owner@legacy.restocloud.local' AND `role` = 'owner'",
    // v53: UNIQUE constraints — split into individual migrations per table for MySQL 5.7 compat
    'v53a_add_unique_segundos' => "ALTER TABLE `segundos` ADD UNIQUE INDEX `uniq_segundos_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53b_add_unique_sopas' => "ALTER TABLE `sopas` ADD UNIQUE INDEX `uniq_sopas_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53c_add_unique_platos_extras' => "ALTER TABLE `platos_extras` ADD UNIQUE INDEX `uniq_platos_extras_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53d_add_unique_gaseosas' => "ALTER TABLE `gaseosas` ADD UNIQUE INDEX `uniq_gaseosas_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53e_add_unique_products' => "ALTER TABLE `products` ADD UNIQUE INDEX `uniq_products_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53f_add_unique_menus' => "ALTER TABLE `menus` ADD UNIQUE INDEX `uniq_menus_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v53g_add_unique_tables' => "ALTER TABLE `tables_config` ADD UNIQUE INDEX `uniq_tables_config_tenant_id` (`tenant_id`, `branch_id`, `id`)",
    'v54_unique_closure_per_day' => "ALTER TABLE `caja_cierres_historico` ADD UNIQUE INDEX `uniq_cierre_per_day` (`tenant_id`, `branch_id`, `fecha`)",
    'v55_create_categories_table' => "CREATE TABLE IF NOT EXISTS `categories` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `name` VARCHAR(100) NOT NULL,
        `type` ENUM('sopa','segundo','plato_extra','refresco','general') NOT NULL DEFAULT 'general',
        `sort_order` INT NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE INDEX `uniq_categories_tenant_branch` (`tenant_id`, `branch_id`, `id`),
        INDEX `idx_categories_tenant_type` (`tenant_id`, `branch_id`, `type`, `active`)
    )",
    'v56_add_category_id_to_products' => "ALTER TABLE `products` ADD COLUMN `category_id` VARCHAR(50) DEFAULT NULL",
    // v57: Stock history tracking for multi-day stock management
    'v57_create_stock_history' => "CREATE TABLE IF NOT EXISTS stock_history (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            item_type ENUM('segundo','sopa','plato_extra','gaseosa') NOT NULL,
            item_id VARCHAR(50) NOT NULL,
            event_type ENUM('set','deduct','restore','adjust') NOT NULL,
            quantity_before INT NOT NULL,
            quantity_change INT NOT NULL,
            quantity_after INT NOT NULL,
            reference_type VARCHAR(50),
            reference_id VARCHAR(50),
            created_at DATETIME NOT NULL,
            INDEX idx_stock_history_item (tenant_id, branch_id, item_type, item_id, created_at),
            INDEX idx_stock_history_date (tenant_id, branch_id, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v58_create_stock_daily_snapshot' => "CREATE TABLE IF NOT EXISTS stock_daily_snapshot (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            item_type ENUM('segundo','sopa','plato_extra','gaseosa') NOT NULL,
            item_id VARCHAR(50) NOT NULL,
            item_name VARCHAR(255) NOT NULL DEFAULT '',
            snapshot_date DATE NOT NULL,
            opening_stock INT NOT NULL,
            closing_stock INT NOT NULL,
            sold_count INT NOT NULL DEFAULT 0,
            UNIQUE KEY uniq_snapshot (tenant_id, branch_id, item_type, item_id, snapshot_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v59_create_discounts' => "CREATE TABLE IF NOT EXISTS discounts (
            id VARCHAR(50) PRIMARY KEY,
            tenant_id VARCHAR(26) NOT NULL,
            branch_id VARCHAR(26) NOT NULL,
            name VARCHAR(255) NOT NULL,
            type ENUM('percentage', 'fixed', 'buy_x_get_y') NOT NULL DEFAULT 'percentage',
            value DECIMAL(10,2) NOT NULL DEFAULT 0,
            min_quantity INT NOT NULL DEFAULT 0,
            free_quantity INT NOT NULL DEFAULT 0,
            applicable_types JSON,
            start_date DATE DEFAULT NULL,
            end_date DATE DEFAULT NULL,
            active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_discounts_tenant (tenant_id, branch_id, active),
            INDEX idx_discounts_dates (start_date, end_date, active)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v60_add_delivery_type_to_reservations' => "ALTER TABLE `reservations` ADD COLUMN `delivery_type` ENUM('para_servirse','para_llevar') NOT NULL DEFAULT 'para_servirse'",
    'v61_add_delivery_type_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `delivery_type` ENUM('mesa','llevar','delivery') NOT NULL DEFAULT 'mesa'",
    // v62: UNIQUE constraints per table (for databases that already ran old v53)
    'v62_fix_tenant_unique_constraints' => "ALTER TABLE `sopas` ADD UNIQUE INDEX `uniq_sopas_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62b_fix_tenant_unique_constraints_platos' => "ALTER TABLE `platos_extras` ADD UNIQUE INDEX `uniq_platos_extras_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62c_fix_tenant_unique_constraints_gaseosas' => "ALTER TABLE `gaseosas` ADD UNIQUE INDEX `uniq_gaseosas_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62d_fix_tenant_unique_constraints_products' => "ALTER TABLE `products` ADD UNIQUE INDEX `uniq_products_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62e_fix_tenant_unique_constraints_menus' => "ALTER TABLE `menus` ADD UNIQUE INDEX `uniq_menus_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    'v62f_fix_tenant_unique_constraints_tables' => "ALTER TABLE `tables_config` ADD UNIQUE INDEX `uniq_tables_config_tenant_id_v2` (`tenant_id`, `branch_id`, `id`)",
    // v63: Add service_state to pedidos for existing databases created before db.php included it
    'v63_add_service_state_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `service_state` VARCHAR(50) DEFAULT NULL",
    'v64_create_salsas_table' => "CREATE TABLE IF NOT EXISTS `salsas` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `tenant_id` VARCHAR(50) NULL,
        `branch_id` VARCHAR(50) NULL
    )",
    'v65_add_accepts_salsa_to_segundos' => "ALTER TABLE `segundos` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v66_add_accepts_salsa_to_sopas' => "ALTER TABLE `sopas` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v67_add_accepts_salsa_to_platos_extras' => "ALTER TABLE `platos_extras` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v68_add_salsa_to_stock_history_enum' => "ALTER TABLE `stock_history` MODIFY COLUMN `item_type` ENUM('segundo','sopa','plato_extra','gaseosa','salsa') NOT NULL",
    'v69_fix_config_precios_pk' => "ALTER TABLE `config_precios` DROP PRIMARY KEY, ADD UNIQUE KEY `uniq_precio` (`id`, `tenant_id`, `branch_id`)",
    'v70_fix_config_general_pk' => "ALTER TABLE `config_general` DROP PRIMARY KEY, ADD UNIQUE KEY `uniq_general` (`id`, `tenant_id`, `branch_id`)",
    'v74_add_paid_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `paid` TINYINT(1) NOT NULL DEFAULT 0",
    'v75_add_pais_to_config_general' => "INSERT IGNORE INTO `config_general` (`id`, `value`) VALUES ('pais', 'Bolivia')",
    'v76_add_trial_days_to_plans' => "ALTER TABLE `plans` ADD COLUMN `trial_days` INT NOT NULL DEFAULT 14",
    'v77_add_plan_snapshot_to_subscriptions' => "ALTER TABLE `tenant_subscriptions` ADD COLUMN `plan_snapshot` JSON DEFAULT NULL",
    'v78_create_plan_changes_log' => "CREATE TABLE IF NOT EXISTS `plan_changes_log` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `old_plan_id` VARCHAR(50) DEFAULT NULL,
        `new_plan_id` VARCHAR(50) DEFAULT NULL,
        `old_snapshot` JSON DEFAULT NULL,
        `new_snapshot` JSON DEFAULT NULL,
        `changed_by` VARCHAR(50) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    'v79_add_payment_verification_to_subscriptions' => "ALTER TABLE `tenant_subscriptions`
        ADD COLUMN `payment_method` VARCHAR(30) DEFAULT NULL,
        ADD COLUMN `payment_notes` TEXT DEFAULT NULL,
        ADD COLUMN `verified_by` VARCHAR(100) DEFAULT NULL,
        ADD COLUMN `verified_at` DATETIME DEFAULT NULL",
    'v80_create_user_branch_access' => "CREATE TABLE IF NOT EXISTS `user_branch_access` (
        `user_id` VARCHAR(50) NOT NULL,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`user_id`, `branch_id`),
        INDEX `idx_user_branch_access_tenant_branch` (`tenant_id`, `branch_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v81_backfill_user_branch_access' => "INSERT IGNORE INTO `user_branch_access` (`user_id`, `tenant_id`, `branch_id`)
        SELECT `id`, `tenant_id`, `branch_id` FROM `users` WHERE `branch_id` IS NOT NULL",
    'v82_grant_owner_access_to_tenant_branches' => "INSERT IGNORE INTO `user_branch_access` (`user_id`, `tenant_id`, `branch_id`)
        SELECT u.`id`, u.`tenant_id`, b.`id` FROM `users` u INNER JOIN `branches` b ON b.`tenant_id` = u.`tenant_id`
        WHERE u.`role` = 'owner' AND u.`active` = 1",
    'v83_add_accepts_salsa_to_products' => "ALTER TABLE `products` ADD COLUMN `accepts_salsa` TINYINT(1) NOT NULL DEFAULT 0",
    'v84_create_whatsapp_processed_messages' => "CREATE TABLE IF NOT EXISTS `whatsapp_processed_messages` (
        `message_id` VARCHAR(150) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `status` ENUM('processing','completed') NOT NULL DEFAULT 'processing',
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `processed_at` DATETIME DEFAULT NULL,
        INDEX `idx_whatsapp_processed_messages_created` (`created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v85_add_reply_to_whatsapp_processed_messages' => "ALTER TABLE `whatsapp_processed_messages` ADD COLUMN `reply` TEXT DEFAULT NULL AFTER `status`",
    'v86_create_whatsapp_events' => "CREATE TABLE IF NOT EXISTS `whatsapp_events` (
        `message_id` VARCHAR(150) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `phone_number_id` VARCHAR(100) NOT NULL,
        `display_phone_number` VARCHAR(30) DEFAULT NULL,
        `sender_phone` VARCHAR(30) NOT NULL,
        `customer_name` VARCHAR(150) DEFAULT NULL,
        `message_text` TEXT NOT NULL,
        `status` ENUM('received','processing','ready','sent','failed') NOT NULL DEFAULT 'received',
        `reply` TEXT DEFAULT NULL,
        `attempts` INT NOT NULL DEFAULT 0,
        `next_attempt_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `last_error` TEXT DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX `idx_whatsapp_events_queue` (`status`, `next_attempt_at`, `created_at`),
        INDEX `idx_whatsapp_events_tenant` (`tenant_id`, `branch_id`, `created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v87_add_sold_at_to_pedidos' => "ALTER TABLE `pedidos` ADD COLUMN `sold_at` DATETIME NULL AFTER `paid`",
    'v87_index_sold_at' => "CREATE INDEX `idx_pedidos_sold_at` ON `pedidos` (`tenant_id`, `branch_id`, `sold_at`, `status`)",
    'v99_add_employee_name_to_financial_expenses' => "ALTER TABLE `gastos_financieros` ADD COLUMN `employee_name` VARCHAR(150) DEFAULT NULL AFTER `reference`",
    'v100_add_payment_period_to_financial_expenses' => "ALTER TABLE `gastos_financieros` ADD COLUMN `payment_period` VARCHAR(50) DEFAULT NULL AFTER `employee_name`",
    'v101_create_order_items_history' => "CREATE TABLE IF NOT EXISTS `pedido_items` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) NOT NULL,
        `line_no` INT NOT NULL,
        `product_id` VARCHAR(50) DEFAULT NULL,
        `item_type` VARCHAR(50) DEFAULT NULL,
        `item_name` VARCHAR(255) NOT NULL,
        `category_id` VARCHAR(50) DEFAULT NULL,
        `category_name` VARCHAR(100) DEFAULT NULL,
        `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `quantity` DECIMAL(10,3) NOT NULL DEFAULT 1,
        `line_total` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `unit_cost` DECIMAL(10,2) DEFAULT NULL,
        `service_type` VARCHAR(50) DEFAULT NULL,
        `item_snapshot` LONGTEXT DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY `uniq_pedido_items_line` (`tenant_id`, `branch_id`, `order_id`, `line_no`),
        INDEX `idx_pedido_items_product_date` (`tenant_id`, `branch_id`, `product_id`, `created_at`),
        INDEX `idx_pedido_items_order` (`tenant_id`, `branch_id`, `order_id`)
    )",
    'v102_create_order_payments_history' => "CREATE TABLE IF NOT EXISTS `pedido_pagos` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) NOT NULL,
        `payment_method` VARCHAR(30) NOT NULL,
        `amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `raw_payment_method` LONGTEXT DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY `uniq_pedido_pagos_method` (`tenant_id`, `branch_id`, `order_id`, `payment_method`),
        INDEX `idx_pedido_pagos_date` (`tenant_id`, `branch_id`, `created_at`)
    )",
    'v103_create_order_discounts_history' => "CREATE TABLE IF NOT EXISTS `pedido_descuentos` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) NOT NULL,
        `discount_id` VARCHAR(50) DEFAULT NULL,
        `discount_name` VARCHAR(255) DEFAULT NULL,
        `discount_type` VARCHAR(50) DEFAULT NULL,
        `amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `basis_amount` DECIMAL(10,2) DEFAULT NULL,
        `discount_snapshot` LONGTEXT DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_pedido_descuentos_order` (`tenant_id`, `branch_id`, `order_id`),
        INDEX `idx_pedido_descuentos_date` (`tenant_id`, `branch_id`, `created_at`)
    )",
    'v104_add_structured_audit_snapshots' => "ALTER TABLE `audit_logs` ADD COLUMN `reason` VARCHAR(255) DEFAULT NULL AFTER `payload`",
    'v105_add_audit_before_snapshot' => "ALTER TABLE `audit_logs` ADD COLUMN `before_snapshot` LONGTEXT DEFAULT NULL AFTER `reason`",
    'v106_add_audit_after_snapshot' => "ALTER TABLE `audit_logs` ADD COLUMN `after_snapshot` LONGTEXT DEFAULT NULL AFTER `before_snapshot`",
    'v107_add_credit_fields_to_orders' => "ALTER TABLE `pedidos` ADD COLUMN `customer_id` VARCHAR(50) DEFAULT NULL AFTER `sold_at`",
    'v108_add_due_date_to_orders' => "ALTER TABLE `pedidos` ADD COLUMN `due_date` DATE DEFAULT NULL AFTER `customer_id`",
    'v109_create_customers' => "CREATE TABLE IF NOT EXISTS `clientes` (
        `id` VARCHAR(50) PRIMARY KEY,
        `name` VARCHAR(150) NOT NULL,
        `phone` VARCHAR(40) DEFAULT NULL,
        `email` VARCHAR(150) DEFAULT NULL,
        `address` VARCHAR(255) DEFAULT NULL,
        `credit_limit` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `active` TINYINT(1) NOT NULL DEFAULT 1,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_clientes_scope_name` (`tenant_id`, `branch_id`, `name`),
        INDEX `idx_clientes_scope_phone` (`tenant_id`, `branch_id`, `phone`)
    )",
    'v110_create_accounts_receivable' => "CREATE TABLE IF NOT EXISTS `cuentas_por_cobrar` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) NOT NULL,
        `customer_id` VARCHAR(50) NOT NULL,
        `original_amount` DECIMAL(10,2) NOT NULL,
        `balance` DECIMAL(10,2) NOT NULL,
        `due_date` DATE NOT NULL,
        `status` ENUM('pendiente','vencida','pagada','cancelada') NOT NULL DEFAULT 'pendiente',
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `closed_at` DATETIME DEFAULT NULL,
        UNIQUE KEY `uniq_cxc_order` (`tenant_id`, `branch_id`, `order_id`),
        INDEX `idx_cxc_scope_status_due` (`tenant_id`, `branch_id`, `status`, `due_date`),
        INDEX `idx_cxc_customer` (`tenant_id`, `branch_id`, `customer_id`)
    )",
    'v112_create_reversals' => "CREATE TABLE IF NOT EXISTS `pedido_reversiones` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) NOT NULL,
        `scope` ENUM('producto_parcial','producto_total','pedido_completo','venta_completa') NOT NULL DEFAULT 'pedido_completo',
        `total_refunded` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `refund_method` VARCHAR(30) NOT NULL DEFAULT 'efectivo',
        `reason` VARCHAR(255) DEFAULT NULL,
        `status` ENUM('aplicada','pendiente','anulada') NOT NULL DEFAULT 'aplicada',
        `created_by` VARCHAR(26) DEFAULT NULL,
        `created_by_name` VARCHAR(150) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_pedido_reversiones_order` (`tenant_id`, `branch_id`, `order_id`),
        INDEX `idx_pedido_reversiones_date` (`tenant_id`, `branch_id`, `created_at`),
        INDEX `idx_pedido_reversiones_scope` (`tenant_id`, `branch_id`, `scope`),
        INDEX `idx_pedido_reversiones_method` (`tenant_id`, `branch_id`, `refund_method`)
    )",
    'v113_create_reversal_items' => "CREATE TABLE IF NOT EXISTS `pedido_reversion_items` (
        `id` VARCHAR(50) PRIMARY KEY,
        `reversal_id` VARCHAR(50) NOT NULL,
        `order_id` VARCHAR(50) NOT NULL,
        `line_no` INT NOT NULL,
        `item_name` VARCHAR(255) NOT NULL,
        `item_type` VARCHAR(50) DEFAULT NULL,
        `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `quantity` DECIMAL(10,3) NOT NULL DEFAULT 1,
        `line_total` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_pedido_reversion_items_reversal` (`reversal_id`),
        INDEX `idx_pedido_reversion_items_order` (`tenant_id`, `branch_id`, `order_id`)
    )",
    'v111_create_receivable_payments' => "CREATE TABLE IF NOT EXISTS `cobros_cuentas_por_cobrar` (
        `id` VARCHAR(50) PRIMARY KEY,
        `receivable_id` VARCHAR(50) NOT NULL,
        `amount` DECIMAL(10,2) NOT NULL,
        `payment_method` VARCHAR(30) NOT NULL DEFAULT 'efectivo',
        `reference` VARCHAR(120) DEFAULT NULL,
        `paid_at` DATETIME NOT NULL,
        `created_by` VARCHAR(26) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        INDEX `idx_cobros_cxc_receivable` (`receivable_id`),
        INDEX `idx_cobros_cxc_date` (`tenant_id`, `branch_id`, `paid_at`)
    )",
    'v114_extend_discounts_channels' => "ALTER TABLE `discounts` ADD COLUMN `channels` JSON DEFAULT NULL AFTER `applicable_types`",
    'v115_extend_discounts_priority' => "ALTER TABLE `discounts` ADD COLUMN `priority` INT NOT NULL DEFAULT 0 AFTER `channels`",
    'v116_extend_discounts_stackable' => "ALTER TABLE `discounts` ADD COLUMN `stackable` TINYINT(1) NOT NULL DEFAULT 0 AFTER `priority`",
    'v117_extend_discounts_coupon' => "ALTER TABLE `discounts` ADD COLUMN `coupon_code` VARCHAR(100) DEFAULT NULL AFTER `stackable`",
    'v118_extend_discounts_limits' => "ALTER TABLE `discounts` ADD COLUMN `max_global_uses` INT DEFAULT NULL AFTER `coupon_code`, ADD COLUMN `max_customer_uses` INT DEFAULT NULL AFTER `max_global_uses`",
    'v119_extend_discounts_requirements' => "ALTER TABLE `discounts` ADD COLUMN `min_subtotal` DECIMAL(10,2) DEFAULT NULL AFTER `max_customer_uses`, ADD COLUMN `applicable_days` JSON DEFAULT NULL AFTER `min_subtotal`, ADD COLUMN `start_hour` TIME DEFAULT NULL AFTER `applicable_days`, ADD COLUMN `end_hour` TIME DEFAULT NULL AFTER `start_hour`",
    'v120_extend_discounts_description' => "ALTER TABLE `discounts` ADD COLUMN `description` TEXT DEFAULT NULL AFTER `name`",
    'v121_extend_discounts_open_order' => "ALTER TABLE `discounts` ADD COLUMN `respetar_cotizaciones_abiertas` TINYINT(1) NOT NULL DEFAULT 0",
    'v122_create_coupon_usage_log' => "CREATE TABLE IF NOT EXISTS `coupon_usage_log` (
        `id` VARCHAR(50) PRIMARY KEY,
        `discount_id` VARCHAR(50) NOT NULL,
        `coupon_code` VARCHAR(100) NOT NULL,
        `order_id` VARCHAR(50) DEFAULT NULL,
        `reservation_id` VARCHAR(50) DEFAULT NULL,
        `customer_id` VARCHAR(50) DEFAULT NULL,
        `used_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        INDEX `idx_coupon_usage_discount` (`tenant_id`, `branch_id`, `discount_id`),
        INDEX `idx_coupon_usage_code` (`tenant_id`, `branch_id`, `coupon_code`),
        INDEX `idx_coupon_usage_customer` (`tenant_id`, `branch_id`, `customer_id`)
    )",
    'v123_create_pedido_cotizaciones' => "CREATE TABLE IF NOT EXISTS `pedido_cotizaciones` (
        `id` VARCHAR(50) PRIMARY KEY,
        `order_id` VARCHAR(50) DEFAULT NULL,
        `reservation_id` VARCHAR(50) DEFAULT NULL,
        `context` ENUM('pos','mesa','llevar','delivery','reserva') NOT NULL DEFAULT 'pos',
        `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `discount_total` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `coupon_code` VARCHAR(100) DEFAULT NULL,
        `coupon_discount` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `manual_discount` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `manual_discount_reason` VARCHAR(255) DEFAULT NULL,
        `manual_discount_authorizer` VARCHAR(150) DEFAULT NULL,
        `total` DECIMAL(10,2) NOT NULL DEFAULT 0,
        `applied_plans` LONGTEXT DEFAULT NULL,
        `status` ENUM('sugerida','seleccionada','bloqueada','retirada','invalidada') NOT NULL DEFAULT 'sugerida',
        `selected_by` VARCHAR(26) DEFAULT NULL,
        `selected_by_name` VARCHAR(150) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `locked_at` DATETIME DEFAULT NULL,
        INDEX `idx_cotizaciones_order` (`tenant_id`, `branch_id`, `order_id`),
        INDEX `idx_cotizaciones_reservation` (`tenant_id`, `branch_id`, `reservation_id`),
        INDEX `idx_cotizaciones_status` (`tenant_id`, `branch_id`, `status`)
    )",
    'v124_pedidos_add_subtotal_discount_columns' => "ALTER TABLE `pedidos` ADD COLUMN `subtotal` DECIMAL(10,2) DEFAULT NULL",
    'v125_pedidos_add_discount_total_column' => "ALTER TABLE `pedidos` ADD COLUMN `discount_total` DECIMAL(10,2) NOT NULL DEFAULT 0",
    'v126_pedidos_add_applied_promo_column' => "ALTER TABLE `pedidos` ADD COLUMN `applied_promo` LONGTEXT DEFAULT NULL",
    'v127_pedidos_add_coupon_code_column' => "ALTER TABLE `pedidos` ADD COLUMN `coupon_code` VARCHAR(100) DEFAULT NULL",
    'v128_create_promo_groups' => "CREATE TABLE IF NOT EXISTS `promo_groups` (
        `id` VARCHAR(50) PRIMARY KEY,
        `discount_id` VARCHAR(50) NOT NULL,
        `group_no` INT NOT NULL DEFAULT 1,
        `quantity_required` INT NOT NULL DEFAULT 1,
        `free_quantity` INT NOT NULL DEFAULT 0,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        INDEX `idx_promo_groups_discount` (`discount_id`, `tenant_id`, `branch_id`)
    )",
    'v129_create_promo_group_products' => "CREATE TABLE IF NOT EXISTS `promo_group_products` (
        `id` VARCHAR(50) PRIMARY KEY,
        `group_id` VARCHAR(50) NOT NULL,
        `product_id` VARCHAR(50) DEFAULT NULL,
        `product_type` VARCHAR(30) NOT NULL,
        `product_name` VARCHAR(150) NOT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        INDEX `idx_promo_group_products_group` (`group_id`, `tenant_id`, `branch_id`)
    )",
    'v130_create_chatbot_conversations' => "CREATE TABLE IF NOT EXISTS `chatbot_conversations` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(50) NOT NULL,
        `branch_id` VARCHAR(50) NOT NULL,
        `wa_phone` VARCHAR(30) NOT NULL,
        `customer_name` VARCHAR(150) DEFAULT NULL,
        `status` ENUM('active','closed') NOT NULL DEFAULT 'active',
        `context` LONGTEXT DEFAULT NULL,
        `reservation_id` VARCHAR(50) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX `idx_chatbot_conversations_tenant_phone` (`tenant_id`, `branch_id`, `wa_phone`, `status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v131_create_chatbot_messages' => "CREATE TABLE IF NOT EXISTS `chatbot_messages` (
        `id` VARCHAR(50) PRIMARY KEY,
        `conversation_id` VARCHAR(50) NOT NULL,
        `role` ENUM('user','assistant','system') NOT NULL,
        `content` LONGTEXT NOT NULL,
        `tool_calls` LONGTEXT DEFAULT NULL,
        `tool_result` LONGTEXT DEFAULT NULL,
        `tokens_in` INT NOT NULL DEFAULT 0,
        `tokens_out` INT NOT NULL DEFAULT 0,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `idx_chatbot_messages_conversation` (`conversation_id`, `created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v132_reservations_add_source' => "ALTER TABLE `reservations` ADD COLUMN `source` VARCHAR(20) NOT NULL DEFAULT 'manual' AFTER `status`",
    'v133_reservations_add_verification_status' => "ALTER TABLE `reservations` ADD COLUMN `verification_status` VARCHAR(20) NOT NULL DEFAULT 'verificada' AFTER `source`",
    'v134_reservations_add_kitchen_printed_at' => "ALTER TABLE `reservations` ADD COLUMN `kitchen_printed_at` DATETIME DEFAULT NULL AFTER `verification_status`",
    'v135_extend_customers_for_crm' => "ALTER TABLE `clientes` ADD COLUMN `phone_normalized` VARCHAR(30) DEFAULT NULL AFTER `phone`, ADD COLUMN `whatsapp_phone` VARCHAR(30) DEFAULT NULL AFTER `phone_normalized`, ADD COLUMN `source` VARCHAR(30) NOT NULL DEFAULT 'manual' AFTER `credit_limit`, ADD COLUMN `notes` TEXT DEFAULT NULL AFTER `source`, ADD COLUMN `marketing_opt_in` TINYINT(1) NOT NULL DEFAULT 0 AFTER `notes`, ADD COLUMN `last_seen_at` DATETIME DEFAULT NULL AFTER `marketing_opt_in`, ADD COLUMN `updated_at` DATETIME DEFAULT NULL AFTER `last_seen_at`, ADD INDEX `idx_clientes_tenant_phone` (`tenant_id`, `phone_normalized`), ADD INDEX `idx_clientes_tenant_name` (`tenant_id`, `name`)",
    'v136_reservations_add_customer_id' => "ALTER TABLE `reservations` ADD COLUMN `customer_id` VARCHAR(50) DEFAULT NULL AFTER `customer_name`, ADD INDEX `idx_reservations_customer` (`tenant_id`, `customer_id`)",
    'v137_chatbot_add_customer_id' => "ALTER TABLE `chatbot_conversations` ADD COLUMN `customer_id` VARCHAR(50) DEFAULT NULL AFTER `customer_name`, ADD INDEX `idx_chatbot_conversations_customer` (`tenant_id`, `customer_id`)",
    'v138_whatsapp_events_add_customer_id' => "ALTER TABLE `whatsapp_events` ADD COLUMN `customer_id` VARCHAR(50) DEFAULT NULL AFTER `customer_name`, ADD INDEX `idx_whatsapp_events_customer` (`tenant_id`, `customer_id`)",
    'v139_create_customer_interactions' => "CREATE TABLE IF NOT EXISTS `customer_interactions` (
        `id` VARCHAR(50) PRIMARY KEY,
        `customer_id` VARCHAR(50) NOT NULL,
        `type` VARCHAR(30) NOT NULL DEFAULT 'nota',
        `content` TEXT NOT NULL,
        `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `created_by` VARCHAR(50) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        INDEX `idx_customer_interactions_customer_date` (`tenant_id`, `customer_id`, `occurred_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v140_create_collection_tasks' => "CREATE TABLE IF NOT EXISTS `collection_tasks` (
        `id` VARCHAR(50) PRIMARY KEY,
        `customer_id` VARCHAR(50) NOT NULL,
        `receivable_id` VARCHAR(50) DEFAULT NULL,
        `status` VARCHAR(20) NOT NULL DEFAULT 'pendiente',
        `due_date` DATE DEFAULT NULL,
        `note` TEXT NOT NULL,
        `completed_at` DATETIME DEFAULT NULL,
        `created_by` VARCHAR(50) DEFAULT NULL,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME DEFAULT NULL,
        INDEX `idx_collection_tasks_customer_status` (`tenant_id`, `customer_id`, `status`, `due_date`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v141_chatbot_add_human_attention' => "ALTER TABLE `chatbot_conversations` ADD COLUMN `attention_mode` VARCHAR(20) NOT NULL DEFAULT 'bot' AFTER `status`, ADD COLUMN `assigned_user_id` VARCHAR(50) DEFAULT NULL AFTER `attention_mode`, ADD COLUMN `assigned_at` DATETIME DEFAULT NULL AFTER `assigned_user_id`, ADD COLUMN `human_takeover_at` DATETIME DEFAULT NULL AFTER `assigned_at`, ADD INDEX `idx_chatbot_attention` (`tenant_id`, `branch_id`, `attention_mode`, `updated_at`)",
    'v142_whatsapp_events_add_held_status' => "ALTER TABLE `whatsapp_events` MODIFY COLUMN `status` ENUM('received','processing','ready','sent','failed','held') NOT NULL DEFAULT 'received'",
    'v143_create_stock_reservations' => "CREATE TABLE IF NOT EXISTS `stock_reservations` (
        `id` VARCHAR(50) PRIMARY KEY,
        `tenant_id` VARCHAR(26) NOT NULL,
        `branch_id` VARCHAR(26) NOT NULL,
        `reference_type` ENUM('order','reservation') NOT NULL,
        `reference_id` VARCHAR(50) NOT NULL,
        `product_id` VARCHAR(50) NOT NULL,
        `quantity` INT NOT NULL,
        `status` ENUM('active','released') NOT NULL DEFAULT 'active',
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `released_at` DATETIME DEFAULT NULL,
        UNIQUE KEY `uniq_stock_reservation_reference_product` (`tenant_id`, `branch_id`, `reference_type`, `reference_id`, `product_id`),
        INDEX `idx_stock_reservation_product` (`tenant_id`, `branch_id`, `product_id`, `status`),
        INDEX `idx_stock_reservation_reference` (`tenant_id`, `branch_id`, `reference_type`, `reference_id`, `status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v144_add_order_reservation_link' => "ALTER TABLE `pedidos` ADD COLUMN `reservation_id` VARCHAR(50) DEFAULT NULL AFTER `customer_id`, ADD UNIQUE INDEX `uniq_pedidos_reservation` (`tenant_id`, `branch_id`, `reservation_id`)",
    'v145_add_reservation_order_link' => "ALTER TABLE `reservations` ADD COLUMN `order_id` VARCHAR(50) DEFAULT NULL AFTER `customer_id`, ADD UNIQUE INDEX `uniq_reservations_order` (`tenant_id`, `branch_id`, `order_id`)",
    'v146_stock_history_supports_canonical_product' => "ALTER TABLE `stock_history` MODIFY COLUMN `item_type` VARCHAR(30) NOT NULL",
    'v147_stock_snapshot_supports_canonical_product' => "ALTER TABLE `stock_daily_snapshot` MODIFY COLUMN `item_type` VARCHAR(30) NOT NULL",
    'v148_add_order_reservation_index' => "ALTER TABLE `pedidos` ADD UNIQUE INDEX `uniq_pedidos_reservation` (`tenant_id`, `branch_id`, `reservation_id`)",
    'v149_add_reservation_order_index' => "ALTER TABLE `reservations` ADD UNIQUE INDEX `uniq_reservations_order` (`tenant_id`, `branch_id`, `order_id`)",
    'v150_financial_expense_closure' => "ALTER TABLE `gastos_financieros` ADD COLUMN `closure_id` VARCHAR(50) DEFAULT NULL AFTER `created_by`, ADD INDEX `idx_gastos_financieros_closure` (`tenant_id`, `branch_id`, `closure_id`)",
    'v151_refund_closure' => "ALTER TABLE `pedido_reversiones` ADD COLUMN `closure_id` VARCHAR(50) DEFAULT NULL AFTER `branch_id`, ADD INDEX `idx_pedido_reversiones_closure` (`tenant_id`, `branch_id`, `closure_id`)",
    'v152_cash_closure_refund_totals' => "ALTER TABLE `caja_cierres_historico` ADD COLUMN `devoluciones_total` DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER `egresos`, ADD COLUMN `devoluciones_efectivo` DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER `devoluciones_total`",
    'v153_create_accompaniments' => "CREATE TABLE IF NOT EXISTS `acompanamientos` (`id` VARCHAR(50) PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `price_extra` DECIMAL(10,2) NOT NULL DEFAULT 0, `active` TINYINT(1) NOT NULL DEFAULT 1, `tenant_id` VARCHAR(26) NOT NULL, `branch_id` VARCHAR(26) NOT NULL, UNIQUE KEY `uniq_acompanamiento_scope_name` (`tenant_id`, `branch_id`, `name`), INDEX `idx_acompanamiento_scope_active` (`tenant_id`, `branch_id`, `active`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    'v154_add_accompaniment_product_settings' => "ALTER TABLE `products` ADD COLUMN `accepts_accompaniment` TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN `max_included_accompaniments` INT NOT NULL DEFAULT 0",
    'v155_add_accompaniment_legacy_settings' => "ALTER TABLE `segundos` ADD COLUMN `accepts_accompaniment` TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN `max_included_accompaniments` INT NOT NULL DEFAULT 0",
    'v156_add_accompaniment_soups_settings' => "ALTER TABLE `sopas` ADD COLUMN `accepts_accompaniment` TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN `max_included_accompaniments` INT NOT NULL DEFAULT 0",
    'v157_add_accompaniment_extra_settings' => "ALTER TABLE `platos_extras` ADD COLUMN `accepts_accompaniment` TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN `max_included_accompaniments` INT NOT NULL DEFAULT 0",
    'v158_products_support_salsa_and_accompaniment' => "ALTER TABLE `products` MODIFY COLUMN `type` ENUM('sopa','segundo','plato_extra','refresco','salsa','acompanamiento') NOT NULL",
    'v159a_unify_discounts_collation' => "ALTER TABLE `discounts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
    'v159b_unify_promo_groups_collation' => "ALTER TABLE `promo_groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
    'v159c_unify_promo_group_products_collation' => "ALTER TABLE `promo_group_products` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
    'v160_discounts_support_menu_price' => "ALTER TABLE `discounts` MODIFY COLUMN `type` ENUM('percentage','fixed','buy_x_get_y','menu_price') NOT NULL DEFAULT 'percentage'",
    'v161_print_order_notes_pickup' => "ALTER TABLE `pedidos` ADD COLUMN `kitchen_note` VARCHAR(500) DEFAULT NULL AFTER `customer`, ADD COLUMN `waiter_note` VARCHAR(500) DEFAULT NULL AFTER `kitchen_note`, ADD COLUMN `pickup_time` TIME DEFAULT NULL AFTER `waiter_note`",
    'v162_print_reservation_notes_pickup' => "ALTER TABLE `reservations` ADD COLUMN `kitchen_note` VARCHAR(500) DEFAULT NULL AFTER `notes`, ADD COLUMN `waiter_note` VARCHAR(500) DEFAULT NULL AFTER `kitchen_note`, ADD COLUMN `pickup_time` TIME DEFAULT NULL AFTER `waiter_note`",
    'v163_order_user_attribution' => "ALTER TABLE `pedidos` ADD COLUMN `created_by_user_id` VARCHAR(50) DEFAULT NULL AFTER `customer`, ADD COLUMN `created_by_name` VARCHAR(150) DEFAULT NULL AFTER `created_by_user_id`, ADD COLUMN `paid_by_user_id` VARCHAR(50) DEFAULT NULL AFTER `created_by_name`, ADD COLUMN `paid_by_name` VARCHAR(150) DEFAULT NULL AFTER `paid_by_user_id`",
    'v164_reservation_user_attribution' => "ALTER TABLE `reservations` ADD COLUMN `created_by_user_id` VARCHAR(50) DEFAULT NULL AFTER `customer_name`, ADD COLUMN `created_by_name` VARCHAR(150) DEFAULT NULL AFTER `created_by_user_id`, ADD COLUMN `confirmed_by_user_id` VARCHAR(50) DEFAULT NULL AFTER `created_by_name`, ADD COLUMN `confirmed_by_name` VARCHAR(150) DEFAULT NULL AFTER `confirmed_by_user_id`, ADD COLUMN `paid_by_user_id` VARCHAR(50) DEFAULT NULL AFTER `confirmed_by_name`, ADD COLUMN `paid_by_name` VARCHAR(150) DEFAULT NULL AFTER `paid_by_user_id`",
];
